#CI项目名
name: CMCC-RAX3000M-NAND-Lede

on:
  #手动编译
  workflow_dispatch:

#CI权限
permissions: write-all

#CI任务
jobs:
  owrt_config:
    #调用公用编译核心OWRT-CORE.yml
    uses: ./.github/workflows/OWRT-RAX3000M-NAND.yml
    with:
      #编译，RAX3000M通用配置
      OWRT_TARGET: RAX3000M-NAND-21.02
      #默认主题
      OWRT_THEME: bootstrap
      #默认主机名
      OWRT_NAME: ImmortalWrt
      #默认地址
      OWRT_IP: 192.168.6.1
      #默认源码
      OWRT_URL: https://github.com/padavanonly/immortalwrt-mt798x
